In [1]:
import numpy as np

def binomial_coeff(n, k):
    """
    Calculate binomial coefficients.

    :param n: Size of the matrix.
    :param k: Element position in the matrix.
    :return: Binomial coefficient.
    """
    if k > n - k:
        k = n - k
    res = 1
    for i in range(k):
        res *= (n - i)
        res //= (i + 1)
    return res


In [15]:

def binomial_matrix(n):
    """
    Generate a binomial matrix.

    :param n: Size of the matrix.
    :return: Binomial matrix of size n x n.
    """
    A = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(i + 1):
            A[i, j] = binomial_coeff(i, j)
            if j != i:
                A[j, i] = A[i, j]  # Symmetric entry
    return A

# Example usage
n = 5
A = binomial_matrix(n)
A_inv = np.linalg.inv(A)
B = A* 2**((1-n)/2)
# matrix_inv = np.linalg.inv(A)
print(B)
print(np.linalg.inv(B))


[[ 0.3415493   0.04225352 -0.07746479  0.00352113 -0.05985915]
 [ 0.04225352 -0.21126761  0.27464789 -0.0528169   0.1971831 ]
 [-0.07746479  0.27464789 -0.12676056  0.22183099 -0.04225352]
 [ 0.00352113 -0.0528169   0.22183099 -0.1056338   0.18309859]
 [-0.05985915  0.1971831  -0.04225352  0.18309859 -0.02816901]]
[[ 2.87256896e+00  8.06326182e-01  1.92314370e-01  1.16958375e-01
   1.18321098e-02]
 [ 8.06326182e-01 -4.75598512e+00 -2.87115492e+00  5.53592273e+00
   5.28489113e+00]
 [ 1.92314370e-01 -2.87115492e+00 -1.68669030e+01  2.50028554e+00
   2.10454580e+01]
 [ 1.16958375e-01  5.53592273e+00  2.50028554e+00 -5.18742145e+00
   1.03425481e+00]
 [ 1.18321098e-02  5.28489113e+00  2.10454580e+01  1.03425481e+00
  -2.33764360e+01]]


In [8]:
def binom(n):
    A = 2**(n-1)*np.eye(n)
    print(np.linalg.inv(A))
n=3
binom(n)

[[0.25 0.   0.  ]
 [0.   0.25 0.  ]
 [0.   0.   0.25]]


In [9]:
import scipy.special as sp

def binomial_matrix(n):
    matrix = [[sp.comb(j, i) for i in range(j + 1)] + [0] * (n - j - 1) for j in range(n)]
    return matrix

# Example usage
n = 5  # size of the matrix
matrix = binomial_matrix(n)
for row in matrix:
    print(row)


[1.0, 0, 0, 0, 0]
[1.0, 1.0, 0, 0, 0]
[1.0, 2.0, 1.0, 0, 0]
[1.0, 3.0, 3.0, 1.0, 0]
[1.0, 4.0, 6.0, 4.0, 1.0]


In [13]:
A_2 = np.array(matrix)
A = np.linalg.inv(A_2)

B = np.linalg.inv(matrix_inv) * 2**((n-1)/2)
print(B)
print(np.linalg.inv(B))



[[ 4.  0.  0.  0.  0.]
 [ 4.  4. -0. -0. -0.]
 [ 4.  8.  4. -0. -0.]
 [ 4. 12. 12.  4. -0.]
 [ 4. 16. 24. 16.  4.]]
[[ 0.25  0.    0.    0.    0.  ]
 [-0.25  0.25  0.    0.    0.  ]
 [ 0.25 -0.5   0.25 -0.   -0.  ]
 [-0.25  0.75 -0.75  0.25 -0.  ]
 [ 0.25 -1.    1.5  -1.    0.25]]


In [16]:
def binomial_coefficient(n, k):
    """Calculate the binomial coefficient 'n choose k'."""
    if k < 0 or k > n:
        return 0
    if k == 0 or k == n:
        return 1
    k = min(k, n - k)  # Take advantage of symmetry
    coeff = 1
    for i in range(k):
        coeff *= (n - i)
        coeff //= (i + 1)
    return coeff

def binomial_matrix(n):
    """Create an n x n binomial matrix."""
    matrix = [[binomial_coefficient(j, i) for i in range(j + 1)] + [0] * (n - j - 1) for j in range(n)]
    return matrix

# Example usage
n = 5  # size of the matrix
matrix = binomial_matrix(n)
matrix



[[1, 0, 0, 0, 0],
 [1, 1, 0, 0, 0],
 [1, 2, 1, 0, 0],
 [1, 3, 3, 1, 0],
 [1, 4, 6, 4, 1]]

In [20]:
import numpy as np

def binomial_matrix(n):
    """Generate an n x n binomial matrix that has the property A^2 = 2^(n-1) * I_n."""
    A = np.zeros((n, n), dtype=int)

    # Filling the binomial matrix
    for i in range(n):
        for j in range(i+1):
            A[i, j] = comb(i, j)
            if i != j:
                A[j, i] = A[i, j]

    return A

def comb(n, k):
    """Compute the binomial coefficient 'n choose k' without using scipy.special.comb."""
    if k > n:
        return 0
    if k == 0 or k == n:
        return 1
    k = min(k, n - k)
    numerator = 1
    denominator = 1
    for i in range(1, k+1):
        numerator *= n + 1 - i
        denominator *= i
    return numerator // denominator

# Example usage:
n = 4  # for a 4x4 matrix
A = binomial_matrix(n)
#print(A)

# Check if the matrix A has the property A^2 = 2^(n-1) * I_n
print(((A), np.power(2, n-1) * np.eye(n)))


(array([[1, 1, 1, 1],
       [1, 1, 2, 3],
       [1, 2, 1, 3],
       [1, 3, 3, 1]]), array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]]))
